name: geo_logistica
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_links: any
  app_links_platform_interface: any
  auto_size_text: any
  cached_network_image: any
  cached_network_image_platform_interface: any
  cached_network_image_web: any
  collection: any
  dropdown_button2: 
    git:
      url: https://github.com/FlutterFlow/dropdown_button2.git
      ref: 514178337dfbea442f617daed39c704b57593fc9
      path: packages/dropdown_button2
  easy_debounce: any
  flutter_animate: any
  flutter_barcode_scanner: 
    git:
      url: https://github.com/FlutterFlow/flutter_barcode_scanner
      ref: 3b315cdeb48e06d1758c5110b3d2dbc3e922a7ce
  flutter_cache_manager: any
  flutter_plugin_android_lifecycle: any
  font_awesome_flutter: any
  from_css_color: any
  # functions_client: any # Deshabilitado para web
  go_router: any
  google_fonts: any
  # gotrue: any # Deshabilitado para web
  hive: any
  intl: any
  json_path: any
  page_transition: any
  path_provider: any
  path_provider_android: any
  path_provider_foundation: any
  path_provider_linux: any
  path_provider_platform_interface: any
  path_provider_windows: any
  # postgrest: 2.5.0 # Deshabilitado para web
  provider: any
  # realtime_client: any # Deshabilitado para web
  rxdart: any
  shared_preferences: any
  shared_preferences_android: any
  shared_preferences_foundation: any
  shared_preferences_linux: any
  shared_preferences_platform_interface: any
  shared_preferences_web: any
  shared_preferences_windows: any
  sign_in_with_apple: any
  sign_in_with_apple_platform_interface: any
  sign_in_with_apple_web: any
  sqflite: any
  sqflite_common: any
  storage_client: any
  signature: ^5.5.0
  pdf: ^3.11.3
  printing: ^5.12.0
  supabase: any
  supabase_flutter: any
  timeago: any
  url_launcher: any
  url_launcher_android: any
  url_launcher_ios: any
  url_launcher_linux: any
  url_launcher_macos: any
  url_launcher_platform_interface: any
  url_launcher_web: any
  url_launcher_windows: any
  webview_flutter: any
  webview_flutter_android: any
  webview_flutter_platform_interface: any
  webview_flutter_wkwebview: any
  share_plus: ^10.0.0

dev_dependencies:
  flutter_lints: any
  lints: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
